Teams = {
	"ANA" : "Anaheim Ducks",
	"ARI" : "Arizona Coyotes",
	"BOS" : "Boston Bruins",
	"BUF" : "Buffalo Sabres",
	"CGY" : "Calgary Flames",
	"CAR" : "Carolina Hurricanes",
	"CHI" : "Chicago Blackhawks",
	"COL" : "Colorado Avalanche",
	"CBJ" : "Columbus Blue Jackets",
	"DAL" : "Dallas Stars",
	"DET" : "Detroit Red Wings",
	"EDM" : "Edmonton Oilers",
	"FLA" : "Florida Panthers",
	"LAK" : "LA Kings",
	"MIN" : "Minnesota Wild",
	"MTL" : "Montreal Canadiens",
	"NSH" : "Nashville Predators",
	"NJD" : "New Jersey Devils",
	"NYI" : "NY Islanders",
	"NYR" : "NY Rangers",
	"OTT" : "Ottawa Senators",
	"PHI" : "Philadelphia Flyers",
	"PIT" : "Pittsburgh Penguins",
	"SJS" : "SJ Sharks",
	"STL" : "St Louis Blues",
	"TBL" : "Tampa Bay Lightning",
	"TOR" : "Toronto Maple Leafs",
	"VAN" : "Vancouver Canucks",
	"WSH" : "Washington Capitals",
	"WPG" : "Winnipeg Jets"
}