TeamCounter = {
	"Anaheim Ducks" : 0,
	"Arizona Coyotes" : 0,
	"Boston Bruins" : 0,
	"Buffalo Sabres" : 0,
	"Calgary Flames" : 0,
	"Carolina Hurricanes" : 0,
	"Chicago Blackhawks" : 0,
	"Colorado Avalanche" : 0,
	"Columbus Blue Jackets" : 0,
	"Dallas Stars" : 0,
	"Detroit Red Wings" : 0,
	"Edmonton Oilers" : 0,
	"Florida Panthers" : 0,
	"LA Kings" : 0,
	"Minnesota Wild" : 0,
	"Montreal Canadiens" : 0,
	"Nashville Predators" : 0,
	"New Jersey Devils" : 0,
	"NY Islanders" : 0,
	"NY Rangers" : 0,
	"Ottawa Senators" : 0,
	"Philadelphia Flyers" : 0,
	"Pittsburgh Penguins" : 0,
	"SJ Sharks" : 0,
	"St Louis Blues" : 0,
	"Tampa Bay Lightning" : 0,
	"Toronto Maple Leafs" : 0,
	"Vancouver Canucks" : 0,
	"Washington Capitals" : 0,
	"Winnipeg Jets": 0,
}